getwd()
titanic=read.csv("titanic.csv",na.strings = "")
View(titanic)
titanic=titanic[-c(1,3,4,9,11)]
titanic$Age[is.na(titanic$Age)]=mean(titanic$Age,na.rm=TRUE)
mean(titanic$Age)
chisq.test(titanic$Survived,titanic$Parch)
chisq.test(titanic$Survived,titanic$SibSp)
chisq.test(titanic$Survived,titanic$Parch)

t.test(Fare ~ Survived, data = titanic)
annova_test=aov(Survived~Parch,data = titanic)
View(annova_test)
summary(annova_test)
library(caTools)
split <- sample.split(titanic, SplitRatio = 0.80)
training_set=subset(titanic,split == TRUE)
test_set=subset(titanic,split == FALSE)
rm(Titanic)
table(titanic$Sex)
model=glm(Survived~.,data = training_set)
summary(model)
test_set$predict_probability <- predict(model, newdata = test_set)
View(test_set)
cor(test_set$Survived,test_set$binary)
test_set$binary=ifelse(test_set$predict_probability>0.50,1,0)
binary=ifelse(test_set$predict_probability>0.50,1,0)
table(test_set$Survived,test_set$binary)
conf_matrix <- confusionMatrix(binary, test_set$Survived)
(135+70)/(135+25+25+70)
